import { ChatEmoji } from "../types";

/** Bộ emoji hay dùng; muốn đủ bộ thì dùng bàn phím emoji của máy */
export const chatEmojis: ChatEmoji[] = [
  { symbol: "😀", label: "Cười" },
  { symbol: "😂", label: "Cười ra nước mắt" },
  { symbol: "🤣", label: "Cười lăn" },
  { symbol: "😊", label: "Mỉm cười" },
  { symbol: "😍", label: "Mắt trái tim" },
  { symbol: "🥰", label: "Yêu thương" },
  { symbol: "😎", label: "Ngầu" },
  { symbol: "🤔", label: "Suy nghĩ" },
  { symbol: "😅", label: "Cười trừ" },
  { symbol: "😭", label: "Khóc" },
  { symbol: "😢", label: "Buồn" },
  { symbol: "😡", label: "Giận" },
  { symbol: "😱", label: "Hoảng" },
  { symbol: "😴", label: "Buồn ngủ" },
  { symbol: "🤯", label: "Nổ não" },
  { symbol: "🥲", label: "Cười mà buồn" },
  { symbol: "🙃", label: "Lộn ngược" },
  { symbol: "😉", label: "Nháy mắt" },
  { symbol: "🤗", label: "Ôm" },
  { symbol: "🤝", label: "Bắt tay" },
  { symbol: "👍", label: "Thích" },
  { symbol: "👎", label: "Không thích" },
  { symbol: "👏", label: "Vỗ tay" },
  { symbol: "🙏", label: "Cảm ơn" },
  { symbol: "💪", label: "Cố lên" },
  { symbol: "👋", label: "Chào" },
  { symbol: "👀", label: "Nhìn" },
  { symbol: "❤️", label: "Trái tim" },
  { symbol: "🔥", label: "Lửa" },
  { symbol: "✨", label: "Lấp lánh" },
  { symbol: "🎉", label: "Chúc mừng" },
  { symbol: "💯", label: "Tuyệt đối" },
  { symbol: "✅", label: "Xong" },
  { symbol: "❌", label: "Sai" },
  { symbol: "⚡", label: "Nhanh" },
  { symbol: "🚀", label: "Tên lửa" },
  { symbol: "💡", label: "Ý tưởng" },
  { symbol: "🐛", label: "Bug" },
  { symbol: "💻", label: "Máy tính" },
  { symbol: "☕", label: "Cà phê" },
];
