export const QUERY_KEYS = {
  GET_LESSON_BY_ID: "GET_LESSON_BY_ID",
  GET_COURSE_BY_SLUG: "GET_COURSE_BY_SLUG",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_LESSON_DETAILS_OUTLINE: "GET_LESSON_DETAILS_OUTLINE",
  GET_LESSONS_BY_COURSE_ID: "GET_LESSONS_BY_COURSE_ID",
};
